### ISSUE TITLE
Small change to prevent certain things from userdata from playing.

### ISSUE THREAD

**Issue by BeigeAnimal** [Lunikc/CustomMenuMusic#1]
Just aheads up, I love what you did with Main Menu Music and the changes you did but I was wondering if you could make a small change. I'm guessing you have it read all .ogg's? I recommend making it read from a folder in User data called "Main Menu Music". I think shit map alert is the only plugin that adds a .ogg to user data, I'm just saying just incase anymore mod author decides to put .ogg there. Also I think it would keep user data clean for the people who like to add multiple songs or even have the folder at the root of the Beat Saber folder and call it "CustomMenuSongs". Just for consistency with the other Custom folders.

**Comment by Lunikc** [comment]
That's a good idea i'll work on it right away ^^ Thanks

**Comment by Lunikc** [comment]
I just released a new version that uses a folder named CustomMenuSongs. But i may not publish it on discord or Beat Saber Installer yet since i just released the first version. Maybe later this week.
